apiVersion: v1
kind: Pod
metadata:
  name: red-pod-a
  namespace: red
  annotations:
    k8s.v1.cni.cncf.io/networks: red/attachnet
spec:
  nodeName: rke2-02
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command: ["sleep", "infinity"]

---
apiVersion: v1
kind: Pod
metadata:
  name: red-pod-b
  namespace: red
  annotations:
    k8s.v1.cni.cncf.io/networks: red/attachnet
spec:
  nodeName: rke2-03
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command: ["sleep", "infinity"]

---
apiVersion: v1
kind: Pod
metadata:
  name: blue-pod-a
  namespace: blue
  annotations:
    k8s.v1.cni.cncf.io/networks: blue/attachnet
spec:
  nodeName: rke2-02
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command: ["sleep", "infinity"]

---
apiVersion: v1
kind: Pod
metadata:
  name: blue-pod-b
  namespace: blue
  annotations:
    k8s.v1.cni.cncf.io/networks: blue/attachnet
spec:
  nodeName: rke2-03
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command: ["sleep", "infinity"]