apiVersion: kubeovn.io/v1
kind: IptablesEIP
metadata:
  name: red-eip
spec:
  natGwDp: red-gw
  externalSubnet: ovn-vpc-external-network
  # v4ip: 10.10.10.82  # if not specified, randomly allocate from pool
---
apiVersion: kubeovn.io/v1
kind: IptablesFIPRule
metadata:
  name: red-fip
spec:
  eip: red-eip
  internalIp: 172.30.0.2