{{- range .Values.pods }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.tenant }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ $.Values.tenant }}/attachnet
        attachnet.{{ $.Values.tenant }}.ovn.kubernetes.io/ip_address: {{ .ip }}
    spec:
      {{- if and $.Values.expose .enableFip }}
      initContainers:
        - name: setup-routing
          image: nicolaka/netshoot
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          command:
            - sh
            - -c
            - |
              set -eux
              ip rule add from {{ .ip }}/32 table 100
              ip route add {{ $.Values.cidr }} dev net1 scope link table 100
              ip route add default via {{ $.Values.lanIp }} dev net1 table 100
      {{- end }}
      containers:
        - name: netshoot
          image: nicolaka/netshoot
          {{- if eq .type "app-a" }}
          command: ["sleep", "infinity"]
          {{- else if eq .type "app-b" }}
          command: ["sleep", "infinity"]
          {{- else }}
          command: ["sleep", "infinity"]
          {{- end }}
{{- end }}
