apiVersion: v1
kind: Namespace
metadata:
  name: __TENANT__
---
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: __TENANT__-vpc
spec: {}
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: attachnet-__TENANT__
spec:
  vpc: __TENANT__-vpc
  protocol: IPv4
  provider: attachnet.__TENANT__.ovn
  cidrBlock: 172.30.0.0/24
  gateway: 172.30.0.1
  excludeIps:
    - 172.30.0.1
    - 172.30.0.254
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: attachnet
  namespace: __TENANT__
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "kube-ovn",
    "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
    "provider": "attachnet.__TENANT__.ovn"
  }'