apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: default/attachnet
spec:
  nodeName: rke2-02
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep","infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  annotations:
    k8s.v1.cni.cncf.io/networks: default/attachnet
spec:
  nodeName: rke2-03
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["sleep","infinity"]