apiVersion: v1
kind: Namespace
metadata:
  name: red
---
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: red-vpc
spec: {}
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: attachnet1-red
spec:
  vpc: red-vpc
  protocol: IPv4
  provider: attachnet1.red.ovn
  cidrBlock: 172.30.1.0/24
  gateway: 172.30.1.1
  excludeIps:
    - 172.30.1.1
    - 172.30.1.254
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: attachnet1
  namespace: red
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "kube-ovn",
    "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
    "provider": "attachnet1.red.ovn"
  }'
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: attachnet2-red
spec:
  vpc: red-vpc
  protocol: IPv4
  provider: attachnet2.red.ovn
  cidrBlock: 172.30.2.0/24
  gateway: 172.30.2.1
  excludeIps:
    - 172.30.2.1
    - 172.30.2.254
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: attachnet2
  namespace: red
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "kube-ovn",
    "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
    "provider": "attachnet2.red.ovn"
  }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  namespace: red
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
      annotations:
        k8s.v1.cni.cncf.io/networks: red/attachnet1
        attachnet1.red.ovn.kubernetes.io/logical_switch: attachnet1-red
        attachnet1.red.ovn.kubernetes.io/ip_address: 172.30.1.2
        # send multus traffic to its gateway
        attachnet1.red.ovn.kubernetes.io/routes: '[{"dst":"172.30.0.0/16","gw":"172.30.1.1"}]'
    spec:
      containers:
        - name: netshoot
          image: nicolaka/netshoot
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  namespace: red
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
      annotations:
        k8s.v1.cni.cncf.io/networks: red/attachnet2
        attachnet2.red.ovn.kubernetes.io/logical_switch: attachnet2-red
        attachnet2.red.ovn.kubernetes.io/ip_address: 172.30.2.2
        attachnet2.red.ovn.kubernetes.io/routes: '[{"dst":"172.30.0.0/16","gw":"172.30.2.1"}]'
        
    spec:
      containers:
        - name: netshoot
          image: nicolaka/netshoot
          command: ["sleep", "infinity"]